version: '2'
services:
  data:
    image: busybox
    volumes:
      - ./misc/data:/var/lib/mysql

  web:
    build: ./web
    container_name: web
    command: DEBUG=tokyo-office:* npm start:dev
    ports:
      - "3000:3000"
    volumes:
      - ../:/var/www/apps
    working_dir: /var/www/apps
    command: [sh, -c, npm install && npm start]
    networks:
      - todo-net

  mysql:
    build: ./mysql
    container_name: mysql
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopass
    ports:
      - "13306:13306"
    volumes_from:
      - data
    networks:
      - todo-net

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "10080:80"
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
